spring.application.name=streakify
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/streakify_db
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional (recommended)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

